### ISSUE TITLE
Local variant raises ModuleNotFoundError

### ISSUE THREAD

**Issue by Pipboyguy** [pathwaycom/llm-app#37]
With `APP_VARIANT=local`, I'm getting the following with the docker workflow:

```console
[+] Building 1.5s (14/14) FINISHED
 => [llm-app-examples internal] load build definition from Dockerfile                                                      0.0s
 => => transferring dockerfile: 579B                                                                                       0.0s
 => [llm-app-examples internal] load .dockerignore                                                                         0.0s
 => => transferring context: 105B                                                                                          0.0s
 => [llm-app-examples internal] load metadata for docker.io/library/python:3.11                                            0.9s
 => [llm-app-examples 1/9] FROM docker.io/library/python:3.11@sha256:9a1b705aecedc76e8bf87dfca091d7093df3f2dd4765af6c2501  0.0s
 => [llm-app-examples internal] load build context                                                                         0.5s
 => => transferring context: 4.54MB                                                                                        0.5s
 => CACHED [llm-app-examples 2/9] WORKDIR /app                                                                             0.0s
 => CACHED [llm-app-examples 3/9] RUN pip install poetry                                                                   0.0s
 => CACHED [llm-app-examples 4/9] RUN poetry config installer.max-workers 10                                               0.0s
 => CACHED [llm-app-examples 5/9] COPY ./pyproject.toml ./pyproject.toml                                                   0.0s
 => CACHED [llm-app-examples 6/9] COPY ./poetry.lock ./poetry.lock                                                         0.0s
 => CACHED [llm-app-examples 7/9] RUN if [ "local" = "local" ] ; then     poetry install --no-root --with examples --no-i  0.0s
 => CACHED [llm-app-examples 8/9] COPY . .                                                                                 0.0s
 => CACHED [llm-app-examples 9/9] RUN poetry install --only-root                                                           0.0s
 => [llm-app-examples] exporting to image                                                                                  0.0s
 => => exporting layers                                                                                                    0.0s
 => => writing image sha256:945b1565afc71f847839a04c11329ebaeea8e274b6187a8177b78a51855c9732                               0.0s
 => => naming to docker.io/library/llm-app-llm-app-examples                                                                0.0s
Traceback (most recent call last):
  File "/app/./run_examples.py", line 144, in <module>
    cli.main()
  File "/app/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/./run_examples.py", line 102, in wrapper
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/app/./run_examples.py", line 112, in local
    return run(**kwargs)
           ^^^^^^^^^^^^^
  File "/app/examples/pipelines/local/app.py", line 58, in run
    embedder = SentenceTransformerTask(model=embedder_locator)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/llm_app/model_wrappers/sentence_transformer/embedding.py", line 11, in __init__
    from sentence_transformers import SentenceTransformer
ModuleNotFoundError: No module named 'sentence_transformers'
```

**Comment by voodoo11** [comment]
Thank you for pointing that out. Fix has already been merged.
